spring.application.name=olimpo_api_nosql

spring.config.import=optional:file:.env[.properties]

# Configuracoes do SQL
spring.datasource.url=${POSTGRES_DB_URL}
spring.datasource.username=${POSTGRES_DB_USER}
spring.datasource.password=${POSTGRES_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracoes do MongoDB
spring.data.mongodb.database=${MONGO_DB_DATABASE}
spring.data.mongodb.uri=${MONGO_DB_URI}

# Limitando o maximo de conexoes no banco
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
